### ISSUE TITLE
IMOS - SRS Satellite - SST L3S - 01 day composite - night time doesn't load in portal

### ISSUE THREAD

**Issue by julian1** [aodn/VIT#21] opened 2017-01-13 00:49 UTC
Maybe it's normal?

**Comment by kereid** [comment] 2017-01-13 00:57
No this isn't normal

**Comment by anguss00** [comment] 2017-01-13 01:21
Caused by old mate caching https://github.com/aodn/thredds/issues/10. Fixed by @lwgordonimos

**Closed by anguss00** 2017-01-13 01:21 UTC
